# Generated by Django 6.0 on 2025-12-07 19:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('dni', models.CharField(blank=True, max_length=20, verbose_name='DNI / CUIT')),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('notas', models.TextField(blank=True, help_text='Comentarios generales sobre el cliente.')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre', 'apellido'],
            },
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_egreso_estimado', models.DateTimeField(blank=True, help_text='Fecha/hora estimada de entrega.', null=True)),
                ('fecha_egreso_real', models.DateTimeField(blank=True, help_text='Fecha/hora real de entrega.', null=True)),
                ('kilometraje', models.PositiveIntegerField(help_text='Kilometraje al momento del trabajo.')),
                ('estado', models.CharField(choices=[('INGRESADO', 'Ingresado'), ('EN_PROCESO', 'En proceso'), ('FINALIZADO', 'Finalizado'), ('ENTREGADO', 'Entregado al cliente'), ('ANULADO', 'Anulado')], default='INGRESADO', max_length=20)),
                ('resumen_trabajos', models.TextField(help_text='Resumen claro y entendible para el comprobante.')),
                ('observaciones_cliente', models.TextField(blank=True, help_text='Lo que comenta el cliente (ruidos, fallas, etc.).')),
                ('observaciones_internas', models.TextField(blank=True, help_text='Notas internas del taller.')),
                ('estado_general', models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('CRITICO', 'Crítico')], default='BUENO', help_text='Evaluación general del vehículo.', max_length=20)),
                ('estado_cubiertas_trabajo', models.CharField(blank=True, help_text='Estado de cubiertas observado en ESTE trabajo.', max_length=200)),
                ('recomendaciones_proximo_service', models.TextField(blank=True, help_text='Cosas a revisar / cambiar en la próxima visita.')),
                ('proximo_control_km', models.PositiveIntegerField(blank=True, help_text='Ej: revisar a los 150.000 km.', null=True)),
                ('total_mano_obra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_repuestos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento total aplicado al trabajo.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('cliente', models.ForeignKey(help_text='Cliente asociado al trabajo (por lo general dueño del vehículo).', on_delete=django.db.models.deletion.PROTECT, related_name='trabajos', to='taller.cliente')),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('DEUDA', 'Deuda generada'), ('PAGO', 'Pago registrado')], max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_cuenta', to='taller.cliente')),
                ('trabajo', models.ForeignKey(blank=True, help_text='Trabajo asociado (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_cuenta', to='taller.trabajo')),
            ],
            options={
                'verbose_name': 'Movimiento de cuenta',
                'verbose_name_plural': 'Movimientos de cuenta',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='TrabajoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MANO_OBRA', 'Mano de obra'), ('REPUESTO', 'Repuesto'), ('INSUMO', 'Insumo'), ('OTRO', 'Otro')], default='MANO_OBRA', max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='taller.trabajo')),
            ],
            options={
                'verbose_name': 'Ítem de trabajo',
                'verbose_name_plural': 'Ítems de trabajo',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('color', models.CharField(blank=True, max_length=50)),
                ('kilometraje_actual', models.PositiveIntegerField(default=0, help_text='Último kilometraje registrado.')),
                ('estado_cubiertas', models.CharField(blank=True, help_text='Ej: Delanteras 70%, traseras 40%.', max_length=200)),
                ('proximo_service_km', models.PositiveIntegerField(blank=True, help_text='Kilometraje sugerido para el próximo control.', null=True)),
                ('proximo_service_fecha', models.DateField(blank=True, help_text='Fecha sugerida para el próximo control.', null=True)),
                ('notas', models.TextField(blank=True, help_text='Observaciones generales del vehículo.')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='taller.cliente')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['patente'],
            },
        ),
        migrations.AddField(
            model_name='trabajo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to='taller.vehiculo'),
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('motivo', models.CharField(help_text='Ej: Service, cambio de embrague, etc.', max_length=255)),
                ('notas', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('CUMPLIDO', 'Cumplido')], default='PENDIENTE', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='taller.cliente')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='taller.vehiculo')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['fecha_hora'],
                'unique_together': {('fecha_hora', 'vehiculo')},
            },
        ),
    ]
