# Generated by Django 6.0 on 2025-12-17 13:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RAPIDO', 'Presupuesto rápido'), ('DETALLADO', 'Presupuesto detallado')], default='DETALLADO', max_length=15)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('valido_hasta', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENTREGADO', 'Entregado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=15)),
                ('titulo', models.CharField(default='Presupuesto', max_length=160)),
                ('resumen', models.TextField(help_text='Resumen claro del presupuesto para el cliente.')),
                ('notas_internas', models.TextField(blank=True)),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento total (solo se muestra si > 0).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', to='taller.cliente')),
                ('vehiculo', models.ForeignKey(blank=True, help_text='Opcional: si todavía no se sabe el vehículo exacto.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', to='taller.vehiculo')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PresupuestoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='taller.presupuesto')),
            ],
            options={
                'verbose_name': 'Ítem de presupuesto',
                'verbose_name_plural': 'Ítems de presupuesto',
            },
        ),
    ]
