# Generated by Django 6.0 on 2025-12-17 21:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_presupuesto_presupuestoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocuenta',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento total (solo se muestra si > 0).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='presupuestoitem',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='presupuestoitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento total aplicado al trabajo.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='total_mano_obra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='total_repuestos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='trabajoitem',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='trabajoitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='movimientocuenta',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gte', 0)), name='movimientocuenta_monto_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='presupuesto',
            constraint=models.CheckConstraint(condition=models.Q(('descuento__gte', 0)), name='presupuesto_descuento_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='presupuesto',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='presupuesto_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='presupuestoitem',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='presupuestoitem_cantidad_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='presupuestoitem',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='presupuestoitem_precio_unitario_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='presupuestoitem',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='presupuestoitem_subtotal_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trabajo',
            constraint=models.CheckConstraint(condition=models.Q(('total_mano_obra__gte', 0)), name='trabajo_total_mano_obra_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trabajo',
            constraint=models.CheckConstraint(condition=models.Q(('total_repuestos__gte', 0)), name='trabajo_total_repuestos_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trabajo',
            constraint=models.CheckConstraint(condition=models.Q(('descuento__gte', 0)), name='trabajo_descuento_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trabajo',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='trabajo_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trabajoitem',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='trabajoitem_cantidad_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='trabajoitem',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='trabajoitem_precio_unitario_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trabajoitem',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='trabajoitem_subtotal_gte_0'),
        ),
    ]
