# Generated by Django 6.0 on 2025-12-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_alter_movimientocuenta_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
