# Generated by Django 5.1.13 on 2026-04-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0004_presupuesto_activo_presupuesto_eliminado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocuenta',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('CHEQUE', 'Cheque'), ('CONTADO', 'Contado')], help_text='Forma en que realizó el pago (solo para pagos).', max_length=20, verbose_name='Método de pago'),
        ),
    ]
