# Generated by Django 5.1.13 on 2026-04-16 13:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0005_movimientocuenta_metodo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_taller', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='taller/logos/')),
                ('moneda', models.CharField(default='$', max_length=5)),
                ('prefijo_nro_trabajo', models.CharField(default='OT', max_length=5)),
            ],
            options={
                'verbose_name': 'Configuración del Taller',
                'verbose_name_plural': 'Configuraciones del Taller',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Producto / Repuesto',
                'verbose_name_plural': 'Productos y Repuestos',
            },
        ),
        migrations.CreateModel(
            name='TrabajoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='trabajos/evidencia/')),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='presupuesto',
            options={'verbose_name': 'Presupuesto', 'verbose_name_plural': 'Presupuestos'},
        ),
        migrations.AlterModelOptions(
            name='presupuestoitem',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='movimientocuenta',
            name='movimientocuenta_monto_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='presupuesto',
            name='presupuesto_descuento_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='presupuesto',
            name='presupuesto_total_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='presupuestoitem',
            name='presupuestoitem_cantidad_gt_0',
        ),
        migrations.RemoveConstraint(
            model_name='presupuestoitem',
            name='presupuestoitem_precio_unitario_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='presupuestoitem',
            name='presupuestoitem_subtotal_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='trabajo',
            name='trabajo_total_mano_obra_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='trabajo',
            name='trabajo_total_repuestos_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='trabajo',
            name='trabajo_descuento_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='trabajo',
            name='trabajo_total_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='trabajoitem',
            name='trabajoitem_cantidad_gt_0',
        ),
        migrations.RemoveConstraint(
            model_name='trabajoitem',
            name='trabajoitem_precio_unitario_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='trabajoitem',
            name='trabajoitem_subtotal_gte_0',
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cliente',
            name='saldo_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='DNI / CUIT'),
        ),
        migrations.AlterField(
            model_name='movimientocuenta',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('CHEQUE', 'Cheque'), ('CONTADO', 'Contado')], max_length=20, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='movimientocuenta',
            name='trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_cuenta', to='taller.trabajo'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='resumen',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', to='taller.vehiculo'),
        ),
        migrations.AlterField(
            model_name='presupuestoitem',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuestoitem',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos', to='taller.cliente'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='estado_cubiertas_trabajo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='estado_general',
            field=models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('CRITICO', 'Crítico')], default='BUENO', max_length=20),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='fecha_egreso_estimado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='fecha_egreso_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='kilometraje',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='observaciones_cliente',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='observaciones_internas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='proximo_control_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='recomendaciones_proximo_service',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='resumen_trabajos',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trabajoitem',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='trabajoitem',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='turno',
            name='motivo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='estado_cubiertas',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='kilometraje_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='proximo_service_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='proximo_service_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajoimagen',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='taller.trabajo'),
        ),
    ]
