# Generated by Django 5.1.13 on 2026-04-16 19:36

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0006_configuraciontaller_producto_trabajoimagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('REPUESTOS', 'Compra de Repuestos'), ('INSUMOS', 'Insumos (Aceite, trapos, etc)'), ('SERVICIOS', 'Servicios (Luz, Alquiler)'), ('OTROS', 'Otros Gastos')], default='REPUESTOS', max_length=20)),
                ('descripcion', models.CharField(help_text='Ej: Pastillas freno Fiesta / Factura EPE', max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('comprobante', models.CharField(blank=True, help_text='Nro de factura o ticket', max_length=50)),
            ],
            options={
                'verbose_name': 'Gasto / Compra',
                'verbose_name_plural': 'Gastos y Compras',
                'ordering': ['-fecha'],
            },
        ),
    ]
