# Generated by Django 5.1.13 on 2026-04-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0007_gasto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='presupuesto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={},
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='fecha_promesa',
            field=models.DateField(blank=True, help_text='Fecha en la que promete pagar la deuda', null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='comprobante',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movimientocuenta',
            name='tipo',
            field=models.CharField(choices=[('DEUDA', 'Deuda generada / Fiado'), ('PAGO', 'Pago registrado')], max_length=10),
        ),
    ]
