# Generated by Django 5.1.13 on 2026-04-17 03:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0008_alter_gasto_options_alter_presupuesto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='resumen_corto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='total_mano_obra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='total_repuestos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='presupuestoitem',
            name='tipo',
            field=models.CharField(choices=[('MANO_OBRA', 'Mano de obra'), ('REPUESTO', 'Repuesto'), ('INSUMO', 'Insumo'), ('OTRO', 'Otro')], default='REPUESTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', to='taller.cliente'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado al Cliente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=15),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='resumen',
            field=models.TextField(blank=True),
        ),
    ]
