# Generated by Django 5.1.13 on 2026-04-20 12:17

import django.db.models.deletion
import taller.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0009_presupuesto_fecha_creacion_presupuesto_resumen_corto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, default=taller.models._generar_token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token API',
                'verbose_name_plural': 'Tokens API',
            },
        ),
        migrations.CreateModel(
            name='PerfilTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del dueño / operador', max_length=100)),
                ('taller_nombre', models.CharField(max_length=150)),
                ('taller_ciudad', models.CharField(blank=True, max_length=100)),
                ('taller_tel', models.CharField(blank=True, max_length=50)),
                ('trial_start', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil del Taller',
                'verbose_name_plural': 'Perfiles de Talleres',
            },
        ),
    ]
