# Generated by Django 5.1.13 on 2026-07-27 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0021_invitaciontaller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoriataller',
            options={'ordering': ['-creado_en']},
        ),
        migrations.AddField(
            model_name='trabajoitem',
            name='completado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='trabajoitem',
            name='completado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajoitem',
            name='completado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_trabajo_completados', to=settings.AUTH_USER_MODEL),
        ),
    ]
