# Generated by Django 5.1.13 on 2026-07-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0024_gasto_metodo_pago_registrado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiltaller',
            name='taller_cuit',
            field=models.CharField(blank=True, max_length=20, verbose_name='CUIT'),
        ),
    ]
