# Generated by Django 5.1.13 on 2026-07-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0025_perfiltaller_taller_cuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiltaller',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='taller/logos/'),
        ),
    ]
