# Generated by Django 5.1.13 on 2026-07-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0027_alter_perfiltaller_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiltaller',
            name='plan_activo_hasta',
            field=models.DateTimeField(blank=True, help_text='Se completa a mano desde el admin al acordar el pago por WhatsApp. Vacío = solo corre el trial.', null=True, verbose_name='Plan pago vigente hasta'),
        ),
    ]
