# Generated by Django 4.2 on 2026-08-05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("taller", "0028_perfiltaller_plan_activo_hasta"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecuperacionContrasena",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token_hash", models.CharField(db_index=True, max_length=64, unique=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("usada_en", models.DateTimeField(blank=True, null=True)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                ("creada_por", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="recuperaciones_creadas", to=settings.AUTH_USER_MODEL)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recuperaciones_contrasena", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Recuperación de contraseña",
                "verbose_name_plural": "Recuperaciones de contraseña",
                "ordering": ["-creada_en"],
            },
        ),
    ]
